{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f7cb9768-c164-469b-bf98-0bb1e6f6df72",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "Integrated FBDD Docking Prep Script\n",
    "-----------------------------------\n",
    "\n",
    "This script automates the following for Windows/Anaconda:\n",
    "\n",
    "1. Prepares ligands in the fragment library (SDF -> PDBQT)\n",
    "2. Prepares representative snapshots as receptor PDBQT\n",
    "3. Generates Vina config files for each KDE peak\n",
    "4. Generates a .bat file with all Vina commands for batch docking\n",
    "\n",
    "Requirements:\n",
    "- Representative snapshots (*_cleaned.pdb) from Step 13c/13d\n",
    "- prepare_protein_snapshots.py script available\n",
    "- AutoDock Vina installed and in PATH\n",
    "- OpenBabel with pybel installed for ligand prep\n",
    "- KDE peak positions from representative_selection_summary.json (Step 13c)\n",
    "\"\"\"\n",
    "\n",
    "import os\n",
    "import json\n",
    "import subprocess\n",
    "from openbabel import openbabel, pybel\n",
    "\n",
    "# -----------------------------\n",
    "# USER INPUTS\n",
    "# -----------------------------\n",
    "snapshots_dir = r\"C:\\Users\\Admin\\Documents\\Documents\\Misc\\FBDD project\\gmx_run_20251119\\post_processing\\full_trajectory\\representative_snapshots\"\n",
    "cleaned_dir = os.path.join(snapshots_dir, \"cleaned_protein_pdbs\")\n",
    "summary_json = os.path.join(snapshots_dir, \"representative_selection_summary.json\")  # Step 13c JSON\n",
    "\n",
    "# need for separate script to prep protein since mgltools/autodocktools uses python 2.7\n",
    "prepare_script = r\"C:\\Users\\Admin\\Documents\\Documents\\Misc\\FBDD project\\AutoDock scripts\\prepare_protein_snapshots.py\"\n",
    "\n",
    "fragments_dir = r\"C:\\Users\\Admin\\Documents\\Documents\\Misc\\FBDD project\\fragment_library\" # ligand input\n",
    "pdbqt_fragments_dir = r\"C:\\Users\\Admin\\Documents\\Documents\\Misc\\FBDD project\\pdbqt_fragment_library\"  # output\n",
    "os.makedirs(pdbqt_fragments_dir, exist_ok=True)\n",
    "\n",
    "docking_dir = r\"C:\\Users\\Admin\\Documents\\Documents\\Misc\\FBDD project\\docking_prep\"\n",
    "os.makedirs(docking_dir, exist_ok=True)\n",
    "\n",
    "box_size = 10.0  # Å, adjust as needed\n",
    "\n",
    "#==============================================================\n",
    "# STEP 1: Prepare ligands\n",
    "#==============================================================\n",
    "print('\\nSTEP 1: Preparing ligands...')\n",
    "def merge_nonpolar_h(mol):\n",
    "    for atom in list(mol):\n",
    "        if atom.atomicnum == 1:\n",
    "            bonded_atoms = [nbr for nbr in openbabel.OBAtomAtomIter(atom.OBAtom)]\n",
    "            if all(nbr.GetAtomicNum() == 6 for nbr in bonded_atoms):\n",
    "                mol.OBMol.DeleteAtom(atom.OBAtom)\n",
    "    return mol\n",
    "\n",
    "sdf_files = [f for f in os.listdir(fragments_dir) if f.lower().endswith(\".sdf\")]\n",
    "ligand_counter = 1\n",
    "prepared_ligands = []\n",
    "\n",
    "print(\"\\nPreparing ligands...\")\n",
    "for sdf_file in sdf_files:\n",
    "    sdf_path = os.path.join(fragments_dir, sdf_file)\n",
    "    for mol in pybel.readfile(\"sdf\", sdf_path):\n",
    "        mol.addh()\n",
    "        mol.calccharges(model=\"gasteiger\")\n",
    "        mol = merge_nonpolar_h(mol)\n",
    "        ligand_name = f\"ligand_{ligand_counter:04d}.pdbqt\"\n",
    "        out_path = os.path.join(pdbqt_fragments_dir, ligand_name)\n",
    "        mol.write(\"pdbqt\", out_path, overwrite=True)\n",
    "        prepared_ligands.append(out_path)\n",
    "        ligand_counter += 1\n",
    "        if ligand_counter % 200 == 0:\n",
    "            print(f\"Prepared {ligand_counter} ligands\")\n",
    "print(f\"Total ligands prepared: {len(prepared_ligands)}\")\n",
    "\n",
    "#==============================================================\n",
    "# STEP 2: Load KDE peaks\n",
    "#==============================================================\n",
    "print('\\nSTEP 2: Loading KDE peaks...')\n",
    "with open(summary_json) as f:\n",
    "    summary = json.load(f)\n",
    "kde_peaks = summary['kde_peak_summary']['peaks_A']  # list of [x,y,z]\n",
    "\n",
    "#==============================================================\n",
    "# STEP 3: Prepare receptors and generate Vina commands\n",
    "#==============================================================\n",
    "print('\\nSTEP 3: Preparing receptors and generating Vina commands...')\n",
    "pdb_files = sorted([f for f in os.listdir(cleaned_dir) if f.endswith(\"_cleaned.pdb\")])\n",
    "vina_commands = []\n",
    "\n",
    "for pdb_file in pdb_files:\n",
    "    pdb_path = os.path.join(cleaned_dir, pdb_file)\n",
    "    pdbqt_out = os.path.join(docking_dir, pdb_file.replace(\".pdb\", \".pdbqt\"))\n",
    "\n",
    "    # Prepare receptor\n",
    "    subprocess.run([\"python\", prepare_script, pdb_path, pdbqt_out], check=True)\n",
    "    print(f\"Prepared receptor: {pdbqt_out}\")\n",
    "\n",
    "    # Generate config & Vina commands for each KDE peak & fragment\n",
    "    for i, peak in enumerate(kde_peaks):\n",
    "        center_x, center_y, center_z = peak\n",
    "        config_file = os.path.join(docking_dir, f\"{pdb_file.replace('.pdb','')}_grid_{i+1}.txt\")\n",
    "\n",
    "        with open(config_file, \"w\") as f:\n",
    "            f.write(f\"receptor = {pdbqt_out}\\n\")\n",
    "            f.write(f\"ligand = ligand.pdbqt\\n\")  # placeholder\n",
    "            f.write(f\"center_x = {center_x:.3f}\\n\")\n",
    "            f.write(f\"center_y = {center_y:.3f}\\n\")\n",
    "            f.write(f\"center_z = {center_z:.3f}\\n\")\n",
    "            f.write(f\"size_x = {box_size}\\n\")\n",
    "            f.write(f\"size_y = {box_size}\\n\")\n",
    "            f.write(f\"size_z = {box_size}\\n\")\n",
    "        print(f\"Generated Vina config: {config_file}\")\n",
    "\n",
    "        # Prepare Vina commands for all ligands\n",
    "        for frag_path in prepared_ligands:\n",
    "            frag_name = os.path.basename(frag_path).replace(\".pdbqt\",\"\")\n",
    "            out_path = os.path.join(docking_dir, f\"{pdb_file.replace('.pdb','')}_grid_{i+1}_{frag_name}_out.pdbqt\")\n",
    "            log_path = out_path.replace(\".pdbqt\", \".log\")\n",
    "            cmd = f\"vina --receptor {pdbqt_out} --ligand {frag_path} --center_x {center_x:.3f} --center_y {center_y:.3f} --center_z {center_z:.3f} --size_x {box_size} --size_y {box_size} --size_z {box_size} --out {out_path} --log {log_path}\"\n",
    "            vina_commands.append(cmd)\n",
    "\n",
    "#==============================================================\n",
    "# STEP 4: Save batch file\n",
    "#==============================================================\n",
    "print('\\nSTEP 4: Saving batch file...')\n",
    "batch_file = os.path.join(docking_dir, \"run_all_vina.bat\")\n",
    "with open(batch_file, \"w\") as f:\n",
    "    for cmd in vina_commands:\n",
    "        f.write(cmd + \"\\n\")\n",
    "\n",
    "print(f\"\\nAll Vina commands saved to {batch_file}\")\n",
    "print(\"Batch docking ready: all receptors, ligands, and config files generated.\")\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
